name: Update ClashX
on:
  schedule:
    - cron: "0 10 * * *"
  # push:
jobs:
  updateClashX:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Latest MetaCubeX/ClashX.Meta Release
        id: clash-meta
        run: |
          release_tag=$(curl -sL https://api.github.com/repos/MetaCubeX/ClashX.Meta/releases/latest | jq -r ".tag_name" | sed "s/v//")
          echo "release_tag=$release_tag" >> $GITHUB_OUTPUT
          current_tag=$(cat Casks/clashx-meta.rb|grep -Po "(\d+)\.(\d+)\.(\*|\d+)")
          echo "current_tag=$current_tag" >> $GITHUB_OUTPUT
      - name: Update ClashX.Meta
        if: steps.clash-meta.outputs.current_tag != steps.clash-meta.outputs.release_tag
        env:
          RELEASE_TAG: ${{ steps.clash-meta.outputs.release_tag }}
          CURRENT_TAG: ${{ steps.clash-meta.outputs.current_tag }}
          CLASHRB: "Casks/clashx-meta.rb"
        run: |
          sed -i "s|$CURRENT_TAG|$RELEASE_TAG|g" $CLASHRB
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update clash-meta to ${{ steps.clash-meta.outputs.release_tag }}
          title: Update ClashX.Meta to ${{ steps.clash-meta.outputs.release_tag }}
          body: |
            Updates [clash-meta][1] to ${{ steps.clash-meta.outputs.release_tag }}

            Auto-generated by [create-pull-request][2]

            [1]: https://github.com/MetaCubeX/ClashX.Meta
            [2]: https://github.com/peter-evans/create-pull-request
          labels: dependencies, automated pr
          branch: clash-meta-updates
