name: Update Gitu
on:
  schedule:
    - cron: "0 10 * * *"
  # push:
jobs:
  updateClashX:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Latest Release
        id: gitu
        run: |
          release_tag=$(curl -sL https://api.github.com/repos/altsem/gitu/releases/latest | jq -r ".tag_name" | sed "s/v//")
          echo "release_tag=$release_tag" >> $GITHUB_OUTPUT
          current_tag=$(cat Formula/gitu.rb|grep -Po "(\d+)\.(\d+)\.(\*|\d+)")
          echo "current_tag=$current_tag" >> $GITHUB_OUTPUT
      - name: Update
        if: steps.gitu.outputs.current_tag != steps.gitu.outputs.release_tag
        env:
          RELEASE_TAG: ${{ steps.gitu.outputs.release_tag }}
          CURRENT_TAG: ${{ steps.gitu.outputs.current_tag }}
          FORMULARB: "Formula/gitu.rb"
        run: |
          sed -i "s|$CURRENT_TAG|$RELEASE_TAG|g" $FORMULARB
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update gitu to ${{ steps.gitu.outputs.release_tag }}
          title: Update gitu to ${{ steps.gitu.outputs.release_tag }}
          body: |
            Updates [gitu][1] to ${{ steps.gitu.outputs.release_tag }}

            Auto-generated by [create-pull-request][2]

            [1]: https://github.com/altsem/gitu
            [2]: https://github.com/peter-evans/create-pull-request
          labels: dependencies, automated pr
          branch: gitu-update
